let translateTextTable = {
    error: 'Error',
    translating_menu_question: 'Do you want to translate the menu of the game?',
    generating_class: 'Generating player classes...',
    scenario_title: 'Scenario',
    scenario_narrative: 'Narrative:',
    choose_player_username: 'Choose your player username',
    choose_game_environment: 'Choose the environment of the game (cyberpunk, medieval, Star Wars, ...)',
    choose_game_environment_default: 'cyberpunk',
    choose_game_difficulty: 'Choose the difficulty of the game (easy, medium, hard, etc.)',
    choose_game_difficulty_default: 'easy',
    choose_player_scenario: 'Write a short scenario for the start of the game (Optional)',
    choose_player_sex: 'Choose the sex of your character',
    choose_player_sex_default: 'male',
    choose_player_description: 'Choose the description of your character and all his traits',
    choose_player_description_default: 'Nothing special',
    select_player_action: 'Choose your next action (1, 2, etc ...) or enter custom action',
    select_player_action_custom: 'Your next action',
    player_level_change: 'Your level is now:',
    player_hp_change: 'Your HP is now:',
    player_mana_change: 'Your mana is now:',
    player_exp_change: 'Your experience is now:',
    player_next_level_exp_change: 'Your next level experience is now:',
    player_money_change: 'Your money is now:',
    player_interface_value_change: 'change',
    player_location_change: 'Your location is now:',
    player_new_quest: 'You have a new quest:',
    player_new_item: 'You got new items:',
    player_lost_item: 'You lost items:',
    accept_ia_answer: 'Accept AI answer?',
    loading_message: 'Loading...',
    translating_text: 'Translating...',
    choose_player_class: 'Choose a class',
    welcome_game: 'Welcome, [username] ! The game is about to start. Have fun!',
    player_start_game: 'Starting the game...',
    shortening_sentence: 'Optimizing text size...',
    init_player_attribute: 'Initializing player attributes...',
    get_narrative_text: 'Generating narrative text...',
    update_inventory_stats: 'Updating player/inventory/location/quest data...',
    generate_game_scenario: 'Generating game scenario...',
    generate_possible_choices: 'Generating possible choices...',
    update_player_inventory: 'Update player inventory...',
    update_player_location: 'Update player location...',
    update_player_quest: 'Update player quest...',
    update_player_stats: 'Update player stats...',
    player_location_reason: 'Location reason:',
    player_location_type: 'Location type:',
    player_location_sublocation: 'Location sublocation:',
    player_quest_description: 'Quest description:',
    player_quest_status: 'Quest status:',
    player_quest_current_step: 'Quest current step:',
    player_quest_total_step: 'Quest total step:',
    player_quest_reward: 'Quest reward:',
    debug_send_stats_data_update: '[DEBUG] Send stats data for update:',
    debug_send_stats_data_updated: '[DEBUG] Got stats data from update:',
    debug_send_location_data_update: '[DEBUG] Send location data for update:',
    debug_send_location_data_updated: '[DEBUG] Got location data from update:',
    debug_send_quest_data_update: '[DEBUG] Send quest data for update:',
    debug_send_quest_data_updated: '[DEBUG] Got quest data from update:',
    debug_send_inventory_data_update: '[DEBUG] Send inventory data for update:',
    debug_send_inventory_data_updated: '[DEBUG] Got inventory data from update:',
    debug_narrive_text_send: '[DEBUG] Data for narrative text:',
    debug_narrive_text_received: '[DEBUG] Narrative text:',
    debug_dont_need_update_player: '[DEBUG] No need to update inventory and stats',
    debug_incorrect_player_data_regenerate: '[DEBUG] Incorrect player data, re-generating ...',
    regenerate_class: "[Regenerate classes]",
    choose_number: 'Choose a number',
    invalid_input: "Invalid input, please enter a number from the list.",
    create_summary_text_history: 'Generating summary from user past choices ...',
    load_save_question: 'Do you want to load a savegame?',
    game_saved: '[SAVE] Game saved !',
    no_possible_choice: 'No possible choice, enter a custom action',
    debug_init_attribute_send: '[DEBUG] Data for init attribute:',
    debug_init_attribute_received: '[DEBUG] Init attribute:',
}

module.exports = translateTextTable;