let translateTextTable = {
    error: 'Error',
    generating_class: 'Generating player classes...',
    choose_player_username: 'Choose your player username',
    choose_game_environment: 'Choose the environment of the game (cyberpunk, medieval, Star Wars, ...)',
    choose_game_environment_default: 'cyberpunk',
    choose_game_difficulty: 'Choose the difficulty of the game (easy, medium, hard, etc.)',
    choose_game_difficulty_default: 'easy',
    choose_player_scenario: 'Write a short scenario for the start of the game (Optional)',
    choose_player_sex: 'Choose the sex of your character',
    choose_player_sex_default: 'male',
    choose_player_description: 'Choose the description of your character and all his traits',
    choose_player_description_default: 'Nothing special',
    select_player_action: 'Choose your next action (1, 2, etc ...) or enter custom action',
    select_player_action_custom: 'Your next action',
    player_level_change: 'Your level is now:',
    player_hp_change: 'Your HP is now:',
    player_mana_change: 'Your mana is now:',
    player_exp_change: 'Your experience is now:',
    player_next_level_exp_change: 'Your next level experience is now:',
    player_money_change: 'Your money is now:',
    player_interface_value_change: 'change',
    player_location_change: 'Your location is now:',
    player_new_quest: 'You have a new quest:',
    player_new_item: 'You got new items:',
    player_lost_item: 'You lost items:',
    accept_ia_answer: 'Accept AI answer?',
    loading_message: 'Loading...',
    translating_text: 'Translating...',
    choose_player_class: 'Choose a class',
    welcome_game: 'Welcome, [username] ! The game is about to start. Have fun!',
    player_start_game: 'Starting the game...',
    shortening_sentence: 'Optimizing text size...',
    init_player_attribute: 'Initializing player attributes...',
    get_narrative_text: 'Generating narrative text...',
    update_inventory_stats: 'Updating player/inventory/location/quest data...',
    generate_game_scenario: 'Generating game scenario...',
    generate_possible_choices: 'Generating possible choices...',
    update_player_inventory: 'Update player inventory...',
    update_player_location: 'Update player location...',
    update_player_quest: 'Update player quest...',
    update_player_stats: 'Update player stats...',

}

module.exports = translateTextTable;